import type { StylePreset } from './types';

export const PRESETS: StylePreset[] = [
  // ========== PHOTOGRAPHY (25) ==========
  {
    id: 'studio-product', name: 'Studio Product', category: 'photography', mode: 'photo',
    aesthetics: 'Clean minimal product photography on seamless white background, commercial studio lighting',
    lighting: 'Soft diffused studio strobes with large softboxes, even wrap-around illumination, no harsh shadows',
    medium: 'photography',
    photo: 'Hasselblad H6D, 100mm f/2.8 macro, ISO 100, 1/250s, tethered capture',
    color_palette: ['#FFFFFF', '#F5F5F0', '#E8E8E0', '#D0D0C8'],
  },
  {
    id: 'fashion-editorial', name: 'Fashion Editorial', category: 'photography', mode: 'photo',
    aesthetics: 'High fashion editorial with dramatic contrast, bold compositions, luxury aesthetic',
    lighting: 'Single beauty dish key light from above, strong directional shadows, minimal fill',
    medium: 'photography',
    photo: 'Canon EOS R5, 50mm f/1.2L, ISO 200, 1/500s, editorial color grade',
    color_palette: ['#1A1A1A', '#FFFFFF', '#C41E3A', '#D4AF37'],
  },
  {
    id: 'golden-hour', name: 'Golden Hour Portrait', category: 'photography', mode: 'photo',
    aesthetics: 'Warm golden hour natural light portrait, dreamy atmosphere with sun flare',
    lighting: 'Late afternoon golden sun as backlight creating rim light, subtle reflector fill from front',
    medium: 'photography',
    photo: 'Sony A7R V, 85mm f/1.4 GM, ISO 100, 1/1000s, natural light only',
    color_palette: ['#F4A460', '#FFD700', '#FFE4B5', '#8B7355'],
  },
  {
    id: 'moody-cinematic', name: 'Moody Cinematic', category: 'photography', mode: 'photo',
    aesthetics: 'Cinematic low-key photography with deep shadows, teal-orange color grading, anamorphic character',
    lighting: 'Single strong key light with grid, deep shadows, practical lights in background for depth',
    medium: 'photography',
    photo: 'ARRI Alexa Mini LF, 35mm anamorphic, T2.8, 800 ISO, cinematic LUT',
    color_palette: ['#0A1628', '#1C3A5C', '#F4A261', '#E76F51'],
  },
  {
    id: 'flat-lay', name: 'Minimalist Flat Lay', category: 'photography', mode: 'photo',
    aesthetics: 'Overhead minimalist flat lay composition, clean geometric arrangement, soft neutrals',
    lighting: 'Large overhead diffused daylight, very even illumination, subtle drop shadow',
    medium: 'photography',
    photo: 'Fujifilm GFX 100S, 120mm f/4 macro, ISO 200, 1/125s, overhead tripod',
    color_palette: ['#FAF9F6', '#E8E2D8', '#D4C9B8', '#B8A99A'],
  },
  {
    id: 'luxury-jewelry', name: 'Luxury Jewelry', category: 'photography', mode: 'photo',
    aesthetics: 'Ultra-luxury jewelry photography on black velvet, pinpoint specular highlights, premium feel',
    lighting: 'Fiber optic pinpoint lights, multiple tiny reflectors for diamond fire, black velvet background',
    medium: 'photography',
    photo: 'Phase One IQ4 150MP, 120mm f/4 macro, focus stacking, ISO 50',
    color_palette: ['#0A0A0A', '#FFD700', '#FFFFFF', '#C0C0C0'],
  },
  {
    id: 'food-photography', name: 'Food Photography', category: 'photography', mode: 'photo',
    aesthetics: 'Appetizing food photography with warm tones, natural textures, soft directional light',
    lighting: 'Large window light from left at 45 degrees, white card fill right, subtle steam',
    medium: 'photography',
    photo: 'Canon EOS R5, 50mm f/1.2 macro, ISO 400, 1/200s, food styling',
    color_palette: ['#8B4513', '#F5DEB3', '#2E8B57', '#CD853F'],
  },
  {
    id: 'real-estate', name: 'Real Estate Interior', category: 'photography', mode: 'photo',
    aesthetics: 'Bright real estate interior photography, wide angle, HDR balanced, inviting spaces',
    lighting: 'Multiple flashes bounced off white ceilings for even ambient fill, window light preserved',
    medium: 'photography',
    photo: 'Sony A7R V, 16-35mm f/2.8 GM at 16mm, ISO 400, bracketed HDR, tripod',
    color_palette: ['#FFFFFF', '#F5F5F0', '#E8E0D5', '#C8B8A0'],
  },
  {
    id: 'night-street', name: 'Night Street', category: 'photography', mode: 'photo',
    aesthetics: 'Atmospheric night street photography, neon reflections on wet pavement, cinematic mood',
    lighting: 'Available neon and street light, deep shadows, shallow depth of field, motion blur',
    medium: 'photography',
    photo: 'Leica M11, 35mm f/1.4 Summilux, ISO 3200, 1/60s, handheld',
    color_palette: ['#0D1117', '#FF1493', '#00CED1', '#FFD700'],
  },
  {
    id: 'vintage-film', name: 'Vintage Film', category: 'photography', mode: 'photo',
    aesthetics: 'Vintage film photography look with warm color cast, subtle grain, Kodak Portra 400 emulation',
    lighting: 'Natural daylight, slightly overexposed for pastel tone, vintage lens character',
    medium: 'photography',
    photo: 'Pentax 67, 105mm f/2.4, Kodak Portra 400 film stock, scanned on Noritsu',
    color_palette: ['#F5E6D0', '#D4B896', '#C4956A', '#8B6914'],
  },
  {
    id: 'bw-fashion', name: 'High Fashion B&W', category: 'photography', mode: 'photo',
    aesthetics: 'Dramatic black and white fashion photography, high contrast, silver gelatin aesthetic',
    lighting: 'Hard single light source creating stark shadows, no fill, deep blacks, bright whites',
    medium: 'photography',
    photo: 'Leica M10 Monochrom, 50mm f/0.95 Noctilux, ISO 400, silver gelatin print look',
    color_palette: ['#0A0A0A', '#2D2D2D', '#808080', '#D0D0D0', '#FFFFFF'],
  },
  {
    id: 'sports-action', name: 'Sports Action', category: 'photography', mode: 'photo',
    aesthetics: 'Dynamic sports action photography, frozen motion, dramatic angles, peak action',
    lighting: 'Fast strobes or available stadium light, high shutter speed to freeze action',
    medium: 'photography',
    photo: 'Canon EOS-1D X Mark III, 200mm f/2L IS, ISO 1600, 1/2000s, servo AF',
    color_palette: ['#003366', '#FF0000', '#FFFFFF', '#00AA00'],
  },
  {
    id: 'macro-nature', name: 'Macro Nature', category: 'photography', mode: 'photo',
    aesthetics: 'Extreme macro nature photography, shallow depth of field, intricate detail, dewdrops',
    lighting: 'Diffused natural light with macro ring flash for fill, focus stacking for depth',
    medium: 'photography',
    photo: 'Nikon Z9, 105mm f/2.8 VR S macro, ISO 200, 1/250s, focus bracket',
    color_palette: ['#228B22', '#8FBC8F', '#DEB887', '#F5F5DC'],
  },
  {
    id: 'architectural', name: 'Architectural', category: 'photography', mode: 'photo',
    aesthetics: 'Precise architectural photography, symmetrical composition, clean lines, blue hour ambient',
    lighting: 'Blue hour twilight with interior lights on, multiple exposures blended, perfect verticals',
    medium: 'photography',
    photo: 'Canon EOS R5, 24mm f/3.5 TS-E tilt-shift, ISO 100, f/11, tripod, bracketed',
    color_palette: ['#1A1A2E', '#16213E', '#0F3460', '#E2E2E2'],
  },
  {
    id: 'underwater', name: 'Underwater', category: 'photography', mode: 'photo',
    aesthetics: 'Ethereal underwater photography, cyan blue cast, floating fabric, weightless movement',
    lighting: 'Sunlight filtering through water surface creating caustic patterns, underwater strobes',
    medium: 'photography',
    photo: 'Nikon Z8 in underwater housing, 14-24mm f/2.8, ISO 800, 1/250s',
    color_palette: ['#006994', '#00B4D8', '#90E0EF', '#CAF0F8'],
  },
  {
    id: 'aerial-drone', name: 'Aerial Drone', category: 'photography', mode: 'photo',
    aesthetics: 'Stunning aerial drone photography, top-down perspective, golden hour light, vast landscapes',
    lighting: 'Golden hour sunlight casting long dramatic shadows, polarizing filter for sky',
    medium: 'photography',
    photo: 'DJI Mavic 3 Pro, Hasselblad 24mm, ISO 100, 1/500s, polarizer, RAW',
    color_palette: ['#87CEEB', '#228B22', '#DAA520', '#8B4513'],
  },
  {
    id: 'documentary', name: 'Documentary', category: 'photography', mode: 'photo',
    aesthetics: 'Authentic documentary photography, available light, unposed moments, photojournalistic',
    lighting: 'Available light only, natural window or ambient, high ISO embraced for grain/texture',
    medium: 'photography',
    photo: 'Leica M6, 35mm f/2 Summicron, Tri-X 400 pushed to 1600, available light',
    color_palette: ['#2D2D2D', '#5C5C5C', '#8B8B8B', '#C0C0C0'],
  },
  {
    id: 'cosmetics-beauty', name: 'Cosmetics Beauty', category: 'photography', mode: 'photo',
    aesthetics: 'Flawless beauty photography, ring light catchlights, perfect skin texture, luxury cosmetics',
    lighting: 'Ring light for signature circular catchlight, softboxes either side, hair light above',
    medium: 'photography',
    photo: 'Hasselblad H6D-100c, 150mm f/2.8, ISO 100, 1/250s, tethered to Capture One',
    color_palette: ['#FFF5EE', '#FFE4E1', '#FFC0CB', '#DDA0DD'],
  },
  {
    id: 'automotive', name: 'Automotive', category: 'photography', mode: 'photo',
    aesthetics: 'Dramatic automotive photography, low angle hero shot, motion blur, polarized reflections',
    lighting: 'Large scrim overhead for soft gradient on bodywork, edge lights for definition, polarizer',
    medium: 'photography',
    photo: 'Canon EOS R5, 24-70mm f/2.8L, ISO 100, 1/30s panning, circular polarizer',
    color_palette: ['#1A1A1A', '#C0C0C0', '#FF0000', '#000080'],
  },
  {
    id: 'wedding', name: 'Wedding', category: 'photography', mode: 'photo',
    aesthetics: 'Romantic wedding photography, soft diffused light, pastel tones, candid emotion',
    lighting: 'Natural window light with soft diffusion, subtle off-camera flash for fill, warm tones',
    medium: 'photography',
    photo: 'Canon EOS R5, 50mm f/1.2L + 85mm f/1.2L, ISO 400, 1/500s, dual card',
    color_palette: ['#FFF0F5', '#FFE4E1', '#F0E6EF', '#E8D5B7'],
  },
  {
    id: 'astrophotography', name: 'Astrophotography', category: 'photography', mode: 'photo',
    aesthetics: 'Breathtaking astrophotography, Milky Way core visible, star trails, cosmic scale',
    lighting: 'Starlight and airglow only, long exposure with star tracker, light painting foreground',
    medium: 'photography',
    photo: 'Sony A7S III modified, 14mm f/1.8 GM, ISO 12800, 20s tracked stack',
    color_palette: ['#0A0A2E', '#1A1A4E', '#4A0E6E', '#FFD700'],
  },
  {
    id: 'wildlife', name: 'Wildlife', category: 'photography', mode: 'photo',
    aesthetics: 'Majestic wildlife photography in natural habitat, golden light, animal portrait',
    lighting: 'Golden hour natural light, eye-level perspective, environmental context',
    medium: 'photography',
    photo: 'Nikon Z9, 400mm f/2.8 TC VR S, ISO 800, 1/2000s, silent shutter',
    color_palette: ['#8B4513', '#556B2F', '#D2B48C', '#87CEEB'],
  },
  {
    id: 'candid-street', name: 'Candid Street', category: 'photography', mode: 'photo',
    aesthetics: 'Candid street photography, high contrast black and white, decisive moment, urban life',
    lighting: 'Available street light and shadow, zone focus for speed, high contrast development',
    medium: 'photography',
    photo: 'Ricoh GR III, 28mm f/2.8, ISO 1600, 1/500s, snap focus at 2m',
    color_palette: ['#1A1A1A', '#4A4A4A', '#808080', '#C0C0C0', '#FFFFFF'],
  },
  {
    id: 'fine-art-nude', name: 'Fine Art Nude', category: 'photography', mode: 'photo',
    aesthetics: 'Fine art nude photography, chiaroscuro lighting, sculptural forms, tasteful elegance',
    lighting: 'Single large window light creating Rembrandt-like chiaroscuro, deep shadow falloff',
    medium: 'photography',
    photo: 'Hasselblad 500C/M, 80mm f/2.8 Planar, Ilford FP4+ 125, fine art print',
    color_palette: ['#1A1A1A', '#3D3D3D', '#6B6B6B', '#A0A0A0', '#F5F0EB'],
  },
  {
    id: 'product-white', name: 'Product on White', category: 'photography', mode: 'photo',
    aesthetics: 'Clean e-commerce product photography on pure white, 360-degree even lighting, zero shadow',
    lighting: '360-degree light tent with 4 daylight-balanced LED panels, bottom light for floating effect',
    medium: 'photography',
    photo: 'Sony A7R V, 90mm f/2.8 macro G, ISO 100, 1/160s, focus stacking',
    color_palette: ['#FFFFFF', '#F8F8F8', '#F0F0F0', '#E8E8E8'],
  },

  // ========== ART & ILLUSTRATION (20) ==========
  {
    id: 'digital-concept', name: 'Digital Concept Art', category: 'art', mode: 'art',
    aesthetics: 'Cinematic digital concept art, photoreal matte painting quality, epic composition',
    lighting: 'Dramatic cinematic lighting with strong key light, volumetric god rays, ambient occlusion',
    medium: 'digital painting',
    art_style: 'Photoreal digital matte painting, concept art quality, cinematic composition, Blender + Photoshop workflow',
    color_palette: ['#1A1A2E', '#16213E', '#E94560', '#0F3460'],
  },
  {
    id: 'oil-painting', name: 'Oil Painting', category: 'art', mode: 'art',
    aesthetics: 'Classical oil painting with visible impasto brushstrokes, rich color depth, traditional mastery',
    lighting: 'Rembrandt lighting characteristic of Dutch Golden Age, warm directional light with chiaroscuro',
    medium: 'oil on canvas',
    art_style: 'Classical oil painting technique, impasto texture, visible brushwork, glazing layers, alkyd medium',
    color_palette: ['#8B4513', '#DAA520', '#800020', '#2F4F4F', '#F5DEB3'],
  },
  {
    id: 'watercolor', name: 'Watercolor', category: 'art', mode: 'art',
    aesthetics: 'Delicate watercolor painting with flowing washes, granulation textures, deckle edge softness',
    lighting: 'Paper white preserved as highlights, transparent layering for luminosity, wet-on-wet blooms',
    medium: 'watercolor on cold-press paper',
    art_style: 'Transparent watercolor, wet-on-wet technique, granulating pigments, preserved white paper, Arches 300gsm',
    color_palette: ['#E8F4F8', '#B8D4E3', '#F0D5D5', '#D4E8C4', '#F5E6CA'],
  },
  {
    id: 'anime-manga', name: 'Anime/Manga', category: 'art', mode: 'art',
    aesthetics: 'Clean anime illustration style with cel shading, vibrant flat colors, expressive character design',
    lighting: 'Two-tone cel shading with sharp shadow transitions, minimal gradients, rim light accents',
    medium: 'digital illustration',
    art_style: 'Modern anime style, crisp line art at 0.3pt, cel shading with 2-3 tones, vibrant color palette, Clip Studio Paint',
    color_palette: ['#FF6B9D', '#4ECDC4', '#FFE66D', '#6C5CE7', '#FF8A5C'],
  },
  {
    id: 'comic-book', name: 'Comic Book', category: 'art', mode: 'art',
    aesthetics: 'Bold comic book illustration with halftone dots, thick outlines, dynamic action, Ben-Day colors',
    lighting: 'High contrast chiaroscuro, heavy black shadows, spot blacks, zip-a-tone texture',
    medium: 'digital illustration',
    art_style: 'American comic book style, Ben-Day dots halftone, bold ink lines, limited color palette, 4-color process',
    color_palette: ['#FF0000', '#0066CC', '#FFCC00', '#000000', '#FFFFFF'],
  },
  {
    id: 'pencil-sketch', name: 'Pencil Sketch', category: 'art', mode: 'art',
    aesthetics: 'Expressive graphite pencil sketch with cross-hatching, varied line weight, textured paper tooth',
    lighting: 'Value-based lighting through graphite density, eraser highlights, atmospheric perspective',
    medium: 'graphite on textured paper',
    art_style: 'Graphite pencil drawing, range 6B-4H, cross-hatching technique, kneaded eraser highlights, Strathmore 400 series',
    color_palette: ['#2B2B2B', '#5C5C5C', '#8C8C8C', '#B8B8B8', '#E8E4D8'],
  },
  {
    id: '3d-render', name: '3D Render', category: 'art', mode: 'art',
    aesthetics: 'Photorealistic 3D render with PBR materials, studio HDRi lighting, subsurface scattering',
    lighting: 'Three-point studio lighting with HDRi environment map, area lights with soft shadows',
    medium: 'CGI / 3D rendering',
    art_style: 'Photorealistic 3D rendering, Octane Render engine, PBR materials, 8K textures, subsurface scattering, ACES color',
    color_palette: ['#FFFFFF', '#E0E0E0', '#A0A0A0', '#606060', '#202020'],
  },
  {
    id: 'pixel-art', name: 'Pixel Art', category: 'art', mode: 'art',
    aesthetics: '16-bit era pixel art with dithering, limited color palette, crisp pixel edges, nostalgic gaming aesthetic',
    lighting: 'Dithering patterns for gradients, sharp lighting with 3-4 shade levels, sprite-style shadows',
    medium: 'pixel art',
    art_style: '16-bit pixel art, indexed color palette, dithering patterns, 64x64 to 128x128 sprite size, Aseprite workflow',
    color_palette: ['#2B2B2B', '#6B3A7D', '#237B8C', '#4BA34B', '#C4A446', '#DB6551'],
  },
  {
    id: 'art-nouveau', name: 'Art Nouveau', category: 'art', mode: 'art',
    aesthetics: 'Ornate Art Nouveau illustration with organic flowing curves, botanical motifs, Mucha-inspired elegance',
    lighting: 'Flat decorative lighting with gold leaf accents, stained glass luminosity, vignette framing',
    medium: 'lithograph print',
    art_style: 'Art Nouveau decorative style, organic whiplash curves, botanical borders, gold leaf accents, Alphonse Mucha influence',
    color_palette: ['#C9A96E', '#8B4513', '#556B2F', '#B8860B', '#F5DEB3'],
  },
  {
    id: 'art-deco', name: 'Art Deco', category: 'art', mode: 'art',
    aesthetics: 'Glamorous Art Deco with geometric symmetry, gold metallics, stepped forms, Gatsby-era luxury',
    lighting: 'Dramatic theatrical spotlighting, metallic surface reflections, neon rim lighting',
    medium: 'digital illustration',
    art_style: 'Art Deco geometric style, symmetrical composition, gold and black palette, stepped ziggurat forms, Great Gatsby era',
    color_palette: ['#000000', '#FFD700', '#C0C0C0', '#1A1A2E', '#E8D5B7'],
  },
  {
    id: 'cyberpunk', name: 'Cyberpunk', category: 'art', mode: 'art',
    aesthetics: 'Gritty cyberpunk with neon-drenched streets, chrome reflections, rain-slicked surfaces, high-tech dystopia',
    lighting: 'Multi-colored neon ambient, volumetric fog, lens flares, screen glow reflections on wet surfaces',
    medium: 'digital painting',
    art_style: 'Cyberpunk digital art, neon-noir palette, Blade Runner aesthetic, volumetric fog, chromatic aberration, synthwave undertones',
    color_palette: ['#0D0221', '#FF003C', '#00FFFF', '#FF00FF', '#FFD700'],
  },
  {
    id: 'steampunk', name: 'Steampunk', category: 'art', mode: 'art',
    aesthetics: 'Victorian steampunk with brass machinery, leather and wood textures, steam vents, clockwork mechanisms',
    lighting: 'Warm gaslight glow, dramatic shadows through gears, steam diffusion, copper reflections',
    medium: 'digital illustration',
    art_style: 'Steampunk illustration, Victorian era aesthetic, brass and copper metallics, gear motifs, steam effects, sepia tone',
    color_palette: ['#8B7355', '#B8860B', '#CD853F', '#4A3728', '#D4A574'],
  },
  {
    id: 'ukiyo-e', name: 'Ukiyo-e', category: 'art', mode: 'art',
    aesthetics: 'Traditional Japanese ukiyo-e woodblock print with flat color planes, bold outlines, nature themes',
    lighting: 'Flat lighting with no shadows, atmospheric gradation (bokashi), negative space clouds',
    medium: 'woodblock print',
    art_style: 'Japanese ukiyo-e woodcut style, bold outlines, flat color planes, bokashi gradient, Hokusai influence, washi paper texture',
    color_palette: ['#2B1810', '#4A3728', '#C44B3C', '#3B6B4A', '#E8D5B7'],
  },
  {
    id: 'pop-art', name: 'Pop Art', category: 'art', mode: 'art',
    aesthetics: 'Bold pop art with silk screen aesthetic, saturated primaries, halftone dots, Warhol-inspired repetition',
    lighting: 'Flat studio lighting with no shadows, high key exposure, commercial print aesthetic',
    medium: 'digital illustration',
    art_style: 'Pop art style, silk screen printing effect, Ben-Day dots, saturated CMYK palette, Warhol and Lichtenstein influence',
    color_palette: ['#FF0000', '#FFFF00', '#0066CC', '#FFFFFF', '#000000'],
  },
  {
    id: 'impressionist', name: 'Impressionist', category: 'art', mode: 'art',
    aesthetics: 'Luminous impressionist painting with broken color, visible dappled brushwork, plein air light',
    lighting: 'Natural sunlight broken through leaves creating dappled light, en plein air quality, color temperature shifts',
    medium: 'oil on canvas',
    art_style: 'French Impressionist style, broken color technique, visible brushstrokes, optical color mixing, Monet and Renoir influence',
    color_palette: ['#87CEEB', '#98FB98', '#F0E68C', '#DDA0DD', '#FFB6C1'],
  },
  {
    id: 'surrealism', name: 'Surrealism', category: 'art', mode: 'art',
    aesthetics: 'Dreamlike surrealism with impossible geometries, melting forms, symbolic juxtapositions, subconscious imagery',
    lighting: 'Sharp theatrical lighting creating hyperreal clarity, long shadows, twilight sky backgrounds',
    medium: 'digital painting',
    art_style: 'Surrealist digital art, dream logic compositions, Dali-esque melting forms, Magritte-inspired juxtapositions, symbolic imagery',
    color_palette: ['#4A90D9', '#F5A623', '#7ED321', '#D0021B', '#2C3E50'],
  },
  {
    id: 'bauhaus', name: 'Bauhaus', category: 'art', mode: 'art',
    aesthetics: 'Minimalist Bauhaus design with geometric abstraction, primary colors, clean functional forms',
    lighting: 'Flat uniform lighting, no shadows, pure form emphasis, architectural clarity',
    medium: 'digital design',
    art_style: 'Bauhaus minimalist style, geometric abstraction, primary red-yellow-blue palette, clean sans-serif typography, form follows function',
    color_palette: ['#E32636', '#FFD700', '#0066CC', '#000000', '#FFFFFF'],
  },
  {
    id: 'vaporwave', name: 'Vaporwave', category: 'art', mode: 'art',
    aesthetics: 'Retro-futuristic vaporwave aesthetic with glitch effects, pastel neon gradients, 80s nostalgia',
    lighting: 'Neon ambient with purple-pink gradients, chrome reflections, VHS scanlines, glitch artifacts',
    medium: 'digital art',
    art_style: 'Vaporwave digital art, pastel neon palette, glitch effects, 80s/90s computer aesthetic, VHS distortion, Greek busts, palm trees',
    color_palette: ['#FF71CE', '#01CDFE', '#05FFA1', '#B967FF', '#FFFB96'],
  },
  {
    id: 'charcoal', name: 'Charcoal Drawing', category: 'art', mode: 'art',
    aesthetics: 'Expressive charcoal drawing with bold gestural marks, smudged atmospheric shading, rough texture',
    lighting: 'Dramatic chiaroscuro through charcoal density, eraser-lifted highlights, sfumato blending',
    medium: 'charcoal on rough paper',
    art_style: 'Charcoal drawing, vine and compressed charcoal, smudge blending, kneaded eraser for highlights, rough tooth paper, gestural marks',
    color_palette: ['#1A1A1A', '#3D3D3D', '#606060', '#8B8B8B', '#D4C9B8'],
  },
  {
    id: 'stained-glass', name: 'Stained Glass', category: 'art', mode: 'art',
    aesthetics: 'Luminous stained glass window with lead came lines, jewel-tone translucent colors, cathedral radiance',
    lighting: 'Back-lit translucency through colored glass, lead line shadow casting, dappled color projection',
    medium: 'stained glass',
    art_style: 'Stained glass art, lead came construction, cathedral glass textures, jewel tone color palette, Gothic and Tiffany influence',
    color_palette: ['#8B0000', '#006400', '#00008B', '#FFD700', '#800080'],
  },

  // ========== CINEMATIC & MIXED (10) ==========
  {
    id: 'hollywood', name: 'Hollywood Blockbuster', category: 'cinematic', mode: 'photo',
    aesthetics: 'Epic Hollywood blockbuster cinematography, anamorphic widescreen, teal-orange grade, lens flares',
    lighting: 'Three-point Hollywood lighting with strong backlight, atmospheric haze, practical set lights',
    medium: 'cinematography',
    photo: 'ARRI Alexa 65, Panavision anamorphic lenses, T2.8, 800 ISO, Michael Bay lens flares',
    color_palette: ['#0A1628', '#1C3A5C', '#F4A261', '#E76F51', '#FFFFFF'],
  },
  {
    id: 'indie-film', name: 'Indie Film', category: 'cinematic', mode: 'photo',
    aesthetics: 'Intimate indie film aesthetic with natural light, handheld camera movement, authentic grit',
    lighting: 'Available light prioritized, practical lamps, bounced window light, minimal grip equipment',
    medium: 'cinematography',
    photo: 'Sony FX3, Zeiss Super Speeds, T1.4, ISO 12800, handheld, A24 look',
    color_palette: ['#2D1B00', '#5C3D1E', '#8B7355', '#C4A882', '#E8DCC8'],
  },
  {
    id: 'noir', name: 'Noir', category: 'cinematic', mode: 'photo',
    aesthetics: 'Classic film noir with deep shadows, venetian blind patterns, rain-slicked streets, cigarette smoke',
    lighting: 'Hard single key light creating stark shadows, venetian blind gobo patterns, practical street lights',
    medium: 'cinematography',
    photo: 'Black and white cinematography, hard lighting, deep focus, 1940s noir aesthetic, 35mm film grain',
    color_palette: ['#0A0A0A', '#1A1A1A', '#4A4A4A', '#808080', '#C0C0C0'],
  },
  {
    id: 'wes-anderson', name: 'Wes Anderson', category: 'cinematic', mode: 'photo',
    aesthetics: 'Whimsical Wes Anderson style with symmetrical composition, pastel color palette, deadpan framing',
    lighting: 'Soft flat frontal lighting, minimal shadows, even exposure, deliberate color temperature',
    medium: 'cinematography',
    photo: 'Symmetrical composition, pastel color palette, 90-degree camera angles, 35mm anamorphic, Kodak film stock',
    color_palette: ['#F4A460', '#87CEEB', '#FFB6C1', '#98FB98', '#DDA0DD'],
  },
  {
    id: 'doc-film', name: 'Documentary Film', category: 'cinematic', mode: 'photo',
    aesthetics: 'Observational documentary style, available light, handheld intimacy, 16mm grain texture',
    lighting: 'Available light only, natural window or practical, high ISO for authenticity, no additional fixtures',
    medium: 'cinematography',
    photo: 'ARRI Amira, Canon 17-120mm Cine-Servo, ISO 1600, handheld, available light, 16mm grain emulation',
    color_palette: ['#3D2B1F', '#5C4A3A', '#8B7355', '#B8A88A', '#D4C9B8'],
  },
  {
    id: 'music-video', name: 'Music Video', category: 'cinematic', mode: 'photo',
    aesthetics: 'High-energy music video with saturated colors, slow motion, stylized lighting, rhythmic editing',
    lighting: 'Dynamic colored LED panels, strobe effects, practical neon, haze machine atmosphere',
    medium: 'cinematography',
    photo: 'RED Komodo, Sigma Cine primes, T1.5, 120fps slow motion, RGB LED panels, haze',
    color_palette: ['#FF0066', '#00FFCC', '#FFD700', '#6600FF', '#FFFFFF'],
  },
  {
    id: 'period-drama', name: 'Period Drama', category: 'cinematic', mode: 'art',
    aesthetics: 'Lush period drama with historical accuracy, painterly composition, warm candlelit interiors',
    lighting: 'Candlelight and window light as motivated sources, warm amber tones, soft period-appropriate illumination',
    medium: 'digital painting',
    art_style: 'Historical period drama aesthetic, oil painting look, Rembrandt lighting, warm amber and gold palette, costume drama',
    color_palette: ['#4A2800', '#8B6914', '#C4956A', '#F5DEB3', '#800020'],
  },
  {
    id: 'sci-fi-epic', name: 'Sci-Fi Epic', category: 'cinematic', mode: 'art',
    aesthetics: 'Vast science fiction epic with photoreal concept art quality, massive scale, cosmic wonder',
    lighting: 'Multiple light sources: distant star, rim light from nebula, practical ship lights, volumetric atmosphere',
    medium: 'digital painting',
    art_style: 'Sci-fi concept art, epic scale, photoreal rendering, cosmic lighting, spaceship design, Dune and Star Wars scale',
    color_palette: ['#0B1021', '#1B2A4A', '#4A6FA5', '#E8A840', '#FFFFFF'],
  },
  {
    id: 'fantasy-illustration', name: 'Fantasy Illustration', category: 'cinematic', mode: 'art',
    aesthetics: 'Epic fantasy illustration with MTG-style quality, rich color saturation, dramatic rim lighting',
    lighting: 'Dramatic rim light separating character from dark background, magical glow effects, atmospheric depth',
    medium: 'digital painting',
    art_style: 'Fantasy illustration, Magic: The Gathering style, dramatic lighting, rich saturated colors, epic scale, high detail',
    color_palette: ['#1A0A2E', '#4A0E6E', '#C44B3C', '#FFD700', '#00CED1'],
  },
  {
    id: 'ghibli', name: 'Ghibli-Inspired', category: 'cinematic', mode: 'art',
    aesthetics: 'Soft painterly Ghibli-inspired illustration with nature focus, warm whimsical atmosphere, detailed backgrounds',
    lighting: 'Soft diffused natural light, warm afternoon glow, dappled forest light, magical particle effects',
    medium: 'digital painting',
    art_style: 'Studio Ghibli inspired, soft painterly style, nature-centric, warm color palette, detailed background art, Miyazaki aesthetic',
    color_palette: ['#87CEEB', '#98FB98', '#F0E68C', '#FFB6C1', '#DDA0DD'],
  },
];

export function getPresetsByCategory(category: string): StylePreset[] {
  return PRESETS.filter((p) => p.category === category);
}
